apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-pipeline-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: image-name
      value: us.icr.io/sn-labs-ashonbaiju12/tax-calculator
  workspaces:
    - name: shared-workspace
      emptyDir: {}
