apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install
spec:
  steps:
    - name: npm-install
      image: node:16
      workingDir: /workspace/source
      script: |
        npm install
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine-tests
spec:
  steps:
    - name: run-tests
      image: node:16
      workingDir: /workspace/source
      script: |
        npx jasmine
